name: throughnothing.com
markdown: redcarpet
pygments: true
paginate: 1
permalink: /:year/:month/:day/:title.html


# Jekyll Plugin Conf Settings

mapping:
    #provider: openstreetmap
    provider: google_js
    api_key: AIzaSyDR_kxahanR8o80ytxAQySRp4nGo7JAmnU
    zoom: 10
    dimensions:
        width: 730
        height: 320


